### PR TITLE
fix niftycloud_lb deregist_instance error

### PR DESCRIPTION
**Pull request by harikiriboy**
Hi,  I find bug.

If there are two or more LBs, and the instance does not exist in the first LB, detachment will fail.

I fixed it. please merge!

### CODE REVIEW

**Comment by ykokw** [comment]
:+1:

**Comment by harikiriboy** [comment]
I fixed test data.

**Comment by tily** [comment]
Tests passed. :+1: 

```
$ git branch
* fix/niftycloud_lb_deregist_instance_error
  master

$ nosetests
.......................................................
----------------------------------------------------------------------
Ran 55 tests in 0.356s

OK

$ nosetests --no-byte-compile --with-coverage > /dev/null 2>&1 && coverage report --include=./niftycloud*.py
Name                   Stmts   Miss  Cover
------------------------------------------
niftycloud.py            165     31    81%
niftycloud_lb.py         118     17    86%
niftycloud_volume.py     100     24    76%
------------------------------------------
TOTAL                    383     72    81%
```

(By the way, I had to `pip install coverage nose mock requests` instead of `pip install unittest mock requests` to run tests. Maybe [library README](https://github.com/NIFTYCloud/ansible-role-niftycloud/blob/master/library/README.md) should be modified?)

**Comment by tily** [comment]
Thanks! @harikiriboy

**Pull request merged**
