### PR TITLE
Fix/print api error response

### PR DESCRIPTION
**Pull request by Blufe**
output error code and error message in log when error is thrown in API request.

```
TASK [niftycloud/run-instances : Run Instances] ********************************
fatal: [e1devops002 -> localhost]: FAILED! => {"changed": false, "error_code": "Client.InvalidParameterNotFound.NetworkName", "error_message": "The NetworkName 'Private2' does not exist.", "failed": true, "instance_id": "e1devops002", "msg": "changes failed (create_instance)", "status": -1}
````

and i updated coverage result.

### CODE REVIEW

**Comment by tily** [comment]
@Blufe Thanks for nice p-r!
It seems that the same `get_api_error` method is declared at 3 places redundantly.
Can you fix to declare it at only 1 place? (by creating `helpers.py` or something like that.)

**Comment by Blufe** [comment]
Apparently the ansible module must be completed with one file.

[http://docs.ansible.com/ansible/dev_guide/developing_modules_best_practices.html](url)
> Modules must be self-contained in one file to be auto-transferred by ansible.

**Comment by tily** [comment]
Tests passed:
```
----------------------------------------------------------------------------------------------
TOTAL                                                                      17506  17178     2%
----------------------------------------------------------------------
Ran 61 tests in 0.584s

OK
Name                   Stmts   Miss  Cover
------------------------------------------
niftycloud.py            178     34    81%
niftycloud_lb.py         125     21    83%
niftycloud_volume.py     105     25    76%
------------------------------------------
TOTAL                    408     80    80%
```
Though the `Miss` count is different from the README ...

**Comment by tily** [comment]
@Blufe Thanks! I got it.

**Pull request merged**
